name: video-codecs-node-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: 'recursive'
    - name: Initialize submodules
      run: git submodule update --init --recursive
    - name: Install dependencies
      run: |
        sudo apt-get update 
        sudo apt-get install --fix-missing -y libavcodec-dev libavfilter-dev libavformat-dev libavutil-dev libswscale-dev libvpx-dev libx264-dev
        sudo wget https://ftp.debian.org/debian/pool/main/a/aom/libaom3_3.10.0-1_amd64.deb
        sudo wget https://ftp.debian.org/debian/pool/main/a/aom/libaom-dev_3.10.0-1_amd64.deb
        sudo dpkg -i libaom3_3.10.0-1_amd64.deb libaom-dev_3.10.0-1_amd64.deb
    - name: Install and build
      run: npm i
    - name: Run Test
      run: npm test
